services:
  mariadb:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: 1234
      DB_NAME: ARCHERYDB
    ports:
      - 3306:3306
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init1.sql
      - ./sample-data.sql:/docker-entrypoint-initdb.d/init2.sql
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ARCHERY_DSN=root:1234@tcp(mariadb:3306)/ARCHERYDB?parseTime=true
    ports:
      - 8000:8000
    depends_on:
      -  mariadb
