CREATE DATABASE ARCHERYDB;
USE DATABASE ARCHERYDB;

CREATE TABLE Member
(
    ArcheryAustraliaID NVARCHAR( 255 ) PRIMARY KEY NOT NULL,
    FirstName NVARCHAR( 255 ),
    DateOfBirth DATE,
    Gender BOOL,
    DefaultBowType NVARCHAR( 255 ),
);

CREATE TABLE Event (
    EventID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(255) NOT NULL,
    Date DATE NOT NULL,
);

CREATE TABLE Championship (
    ChampionshipID INT PRIMARY KEY NOT NULL ,  
    EventID INT NOT NULL,
    Name VARCHAR(255) NOT NULL,
    FOREIGN KEY (EventID) 
        REFERENCES Event(EventID)
);
