CREATE DATABASE IF NOT EXISTS ARCHERYDB;
USE ARCHERYDB;

CREATE TABLE IF NOT EXISTS Member
(
    ArcheryAustraliaID NVARCHAR( 255 ) PRIMARY KEY NOT NULL,
    FirstName NVARCHAR( 255 ),
    DateOfBirth DATE,
    Gender BOOL,
    DefaultBowType NVARCHAR( 255 ),
);

CREATE TABLE Round (
    RoundID INT AUTO_INCREMENT PRIMARY KEY,
    EventID INT NOT NULL,
    Division VARCHAR(255) NOT NULL,
    Class VARCHAR(255) NOT NULL,
    Gender BOOL,
    FOREIGN KEY (EventID) REFERENCES Event(EventID),
    FOREIGN KEY (Division) REFERENCES Division(DivisionID),
    FOREIGN KEY (Class) REFERENCES Class(ClassID)
);
  
CREATE TABLE Range (
    RangeID INT AUTO_INCREMENT PRIMARY KEY,
    RoundID INT NOT NULL,
    Staged BOOL NOT NULL,
    Distance INT NOT NULL,
    TargetSize INT NOT NULL,
    FOREIGN KEY (RoundID) REFERENCES Round(RoundID)
);

CREATE TABLE IF NOT EXISTS PracticeEvent
(
    PracticeID INT AUTO_INCREMENT PRIMARY KEY,
    EventID INT NOT NULL,
    ArcheryAustraliaID NVARCHAR( 255 ) NOT NULL,
    FOREIGN KEY (EventID) REFERENCES Event(EventID),
    FOREIGN KEY (ArcheryAustraliaID) REFERENCES Member(ArcheryAustraliaID)
);

CREATE TABLE IF NOT EXISTS End
(
    EndID INT AUTO_INCREMENT PRIMARY KEY,
    RangeID INT NOT NULL,
    ArcheryAustraliaID NVARCHAR( 255 ) NOT NULL,
    FinalScore INT,
    FOREIGN KEY (RangeID) REFERENCES Range(RangeID),
    FOREIGN KEY (ArcheryAustraliaID) REFERENCES Member(ArcheryAustraliaID)
);

CREATE TABLE IF NOT EXISTS Score
(
    ScoreID INT AUTO_INCREMENT PRIMARY KEY,
    EndID INT NOT NULL,
    ArrowNumber INT,
    Score INT,
    FOREIGN KEY (EndID) REFERENCES End(EndID)
);
CREATE TABLE IF NOT EXISTS Class(
    ClassID INT AUTO_INCREMENT PRIMARY KEY,
    PRIMARY KEY ( ClassID )
);
