// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package data

import (
	"time"
)

type Championship struct {
	Championshipid int32
	Eventid        int32
	Name           string
}

type Class struct {
	Classid string
}

type Division struct {
	Divisionid string
}

type End struct {
	Endid              int32
	Rangeid            int32
	Archeryaustraliaid string
	Finalscore         int32
}

type Event struct {
	Eventid int32
	Name    string
	Date    time.Time
}

type Member struct {
	Archeryaustraliaid string
	Passwordhash       string
	Firstname          string
	Dateofbirth        time.Time
	Gender             bool
	Clubrecorder       bool
	Defaultdivision    string
}

type Practiceevent struct {
	Practiceid         int32
	Eventid            int32
	Archeryaustraliaid string
}

type Range struct {
	Rangeid    int32
	Roundid    int32
	Staged     bool
	Distance   int32
	Targetsize int32
}

type Round struct {
	Roundid  int32
	Eventid  int32
	Division string
	Class    string
	Gender   bool
}

type Score struct {
	Scoreid     int32
	Endid       int32
	Arrownumber int32
	Score       int32
}
